name: 'Cargo Semver Update'
icon: at-sign
color: black
description: 'Update Cargo.toml version with Semver #major #minor #patch.'
outputs:
  new_version:
    description: 'new semver version'
  new_version_with_v:
    description: 'new semver version with v'
runs:
  using: 'Docker'
  image: 'Dockerfile'
